global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Алерты
rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['app:3000']
